### ISSUE TITLE
SPARQL documentation

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#153] opened 2019-07-05 15:22 UTC
In looking to craft additional SPARQL queries, I noticed that the examples refer to things that are not documented within the "Properties defined in PRO" page (https://proconsortium.org/pro_doc.shtml). For example, query 13 refers to "?gn_id" and query 3 refers to "?mod" but neither of these are described on the indicated page. I understand that the page refers specifically to properties, but perhaps we can expand it? Even a list of possible fields would be a useful start. Can such be generated automatically?

**Comment by chumingc** [comment] 2019-07-05 15:36
pro_doc.shtml was intended to list predicates used in PRO in terms of triple. ?gn_id is not. ?mod is a hacking to do regex search in string representation of rdfs:comment.

If we expend this to list all possible subjects and objects, that will be overwhelming considering the size of PRO.

Chuming

**Comment by nataled** [comment] 2019-07-05 15:46
When you say "all possible subjects and objects" do you refer to the precise strings? Because surely the number of *fields* that we can query on is not huge--it would be the same size even if PRO was (for example) one-tenth the current size. Other than by reviewing every possible sample query, how would a user know that they can look for ?glp (gene-level parent). Even after reviewing them all, the list would likely be incomplete.

**Comment by chumingc** [comment] 2019-07-05 16:20
We should identify patterns how PRO terms are described in RDF. Instead of a single triple, a pattern will be a set of triples (a sub graph of PRO), for example, result of a describe query in SPRAQL We then provide unique patterns for the users as the examples. ?glp (gene-level parent) will be in one of the pattern, although may not be exactly called “general_level parent”. SPARQL is using graph pattern match, once users see the pattern, they know how to write the query. That’s how I came up with the example queries.

Chuming

**Comment by nataled** [comment] 2019-07-05 17:39
What you are saying isn't fully correct. Even knowing that "PR:000049129 only_in_taxon NCBITaxon:9606" can be abstracted into a pattern (such as "?PRO_identifier only_in_taxon ?NCBITaxon_identifier"), the user would still need to know the precise variable names used in the subject and object. I know from the sample queries that what I called above "PRO_identifier" is actually called "PRO_term" but I shouldn't have to look at the samples to find this information, especially since the samples don't contain all the possible variables. The fact that these variable names are not documented hampers the ability to create new queries or customize the output. For example, let's say I want to add a column to the output that displays the taxon identifier. I can tell from the sample queries that in UniProt I'd use "?organism" to do it. But that same variable name doesn't work in PRO (nor does "?_organism" or "?org" or "?_org" or "?taxonomy" or "?NCBITaxon" etc etc). I also can tell that using "?pro_term" instead of "?PRO_term" will not work, so these variable names must be encoded somehow.

**Comment by chumingc** [comment] 2019-07-05 18:04
variable in SPRAQL is a place holder, just like variable in other programming language. How do you name it does not matter. The thing matters is the triple patterns and where this variable is located in the rdf triple in your query.  variables are case sensitive. ?abc and ?ABC are different. They do not map to same bindings for the query. In a given query, "?_organism” and "?org” are different. The point is you are not required to name it ?org or ?_organism. You can call it whatever you want. 

Chuming

**Comment by nataled** [comment] 2019-07-05 18:21
I think we aren't understanding each other. I know I can name a variable anything I want, and I know that it is just a placeholder. But once that variable name is decided, it cannot be called something else. So if I define variable "$name" in my program/script (using perl syntax just as example), and I want to display the contents of that variable, I cannot say "print $label" within that program and expect any result. 

What I described in my previous reply was a real case: I took one of the sample queries, and tried to add a column to the result to display the organism. A very simple change, but I couldn't do it *even knowing that there is definitely a field for this* in PRO. But since I didn't know the name of the field/variable, I failed to get any information in the column. This is why the variable name documentation is needed.

**Comment by chumingc** [comment] 2019-07-05 18:37
You can't simply add a variable in the select clause, it needs to be somehow related to at least one of the triples in the query.

That is why I mentioned triple patterns. For the PRO evolutionary term with category family (PR:000000027), if we present the following RDF triples as example. User will be able to identify what the “field” is and where it should be in SPARQL query.

@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix obo:	<http://purl.obolibrary.org/obo/> .
@prefix owl:	<http://www.w3.org/2002/07/owl#> .
@prefix xsd:	<http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .
@prefix oboInOwl:	<http://www.geneontology.org/formats/oboInOwl#> .
@prefix paf:	<http://pir.georgetown.edu/pro/paf#> .

obo:PR_000000027	rdf:type	owl:Class , rdf:resource .
obo:PR_000000027	
        rdfs:label	"smad protein"^^xsd:string ;
	rdfs:comment	"Category=family."^^xsd:string ;
	rdfs:subClassOf	obo:PR_000000001 .
obo:PR_000000027	
        oboInOwl:hasDbXref	"PIRSF:PIRSF037286"^^xsd:string ;
	oboInOwl:hasOBONamespace	"protein"^^xsd:string ;
	oboInOwl:id	"PR:000000027"^^xsd:string ;
	obo:IAO_0000115	"A protein with core domain composition consisting of one MH1 domain (Pfam:PF03165) at the N terminus and one MH2 domain (Pfam:PF03166) at the C-terminus, separated by a non-conserved linker region. Smad proteins are mediators of signal transduction in transforming growth factor beta (TGF-beta) superfamily pathways."^^xsd:string .

**Comment by nataled** [comment] 2019-07-05 19:13
> You can't simply add a variable in the select clause, it needs to be somehow related to at least one of 
> the triples in the query. 

Okay, good, we're getting closer to understanding each other. This is almost what I'm talking about. I say almost because I'm already able to see all of what you show above using DESCRIBE. Of concern to me are those things I cannot see. Sticking with taxonomy as an example, and using a species specific term, the following *does not* show that the indicated protein has some associated information about taxonomy, even though it for sure is in the OWL:

DESCRIBE <http://purl.obolibrary.org/obo/PR_000049129>

Now suppose I want to do the query that we have as sample query #1 on our SPARQL page, but I want to add a column for Taxon. As you said earlier, I can make up any variable name for the display simply by adding it to the SELECT command:

SELECT ?PRO_term ?Label ?Category ?Taxon

Of course, this by itself is not enough, because internally there is no such thing as ?Taxon. I'd have to BIND the actual variable name to that ?Taxon:

<pre>BIND(str(?_NCBITaxon) as ?Taxon)
         ^^^^^^^^^^^</pre>

The problem is that I have no idea what should be in place of ?_NCBITaxon to make the query work.

Now, if you are saying such information isn't in the RDF (which would be exceedingly surprising), that's one thing. So let's take another example mentioned before (?glp) which definitely is something that can be queried. If I'm not the person that designed the endpoint, and there were no sample queries provided, how would I go about finding out that ?glp has meaning?

**Comment by chumingc** [comment] 2019-07-05 19:36
On Jul 5, 2019, at 3:14 PM, Darren A. Natale <notifications@github.com> wrote:

> Now, if you are saying such information isn't in the RDF (which would be exceedingly surprising), that's one thing. So let's take another example mentioned before (?glp) which definitely is something that can be queried. If I'm not the person that designed the endpoint, and there were no sample queries provided, how would I go about finding out that ?glp has meaning?

You need to know the “triple pattern” around the term to come up with query. If there is no sample queries, you can download the ontology and convert it to turtle format and take a look yourself. At least, that what I did. You know PRO inside out, but for me, looking through turtle file helped me to come up the SPARQL query.

Providing sample triple patterns for different types of PRO terms I mentioned before is certainly a step moving forward. Otherwise, people need to download the ontology and dig out themselves. However, just providing the properties or variables individually without the context (subgraph) will not help.

By the way, I know “Describe” query can not give you complete answer, I was using it as an example. If there is any additional information which is important for a given type of PRO term, we should include those triples as the sample triple pattern.

Chuming

**Comment by nataled** [comment] 2019-07-05 20:01
So in order to find out the names of variables to use in a query, I can convert PRO to turtle, and examine the output? Seems very strange, but I can try it. Based on your comments, I would expect that I'd be able to reproduce your finding that (for example) ?_Category means the PRO category, while ?category does not. Is that correct?

**Comment by chumingc** [comment] 2019-07-05 20:10
In the query below, ?_Category is part of triple pattern, regex was used to remove “=“ and “.”, and then bind the result to new variable ?Category, then used in select clause.


SELECT ?PRO_term ?Label ?Category
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:label ?_Label .
   ?PRO_term rdfs:comment ?_Category .
   FILTER (regex(?_Category,"Category=.*modification"))
   BIND(str(?_Label) as ?Label) .
   BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
}

**Comment by nataled** [comment] 2019-07-05 20:16
This is obvious after the fact, but I want to know how you knew that ?_Category is part of the triple pattern. How did you know that you needed to say

 ?PRO_term rdfs:comment ?_Category . 

instead of 

 ?PRO_term rdfs:comment ?category . 

Based on your previous response, it is indicated by the turtle view of the ontology, presumably there is some place that, using turtle, I'd somewhere see the string "_Category" but not see the string "category". I just want confirmation that I correctly understand what you're saying.

**Comment by chumingc** [comment] 2019-07-05 20:30
Here is the turtle for PR_000018259. There is only rdfs:comment string value  "Category=modification.”.

The triple pattern is 
?PRO_term rdfs:comment ?_Category .

I used variable ?_Category to get rdfs:comment string value, then do regex processing to get “modification” as the value returned in the select clause.



obo:PR_000018259  a               owl:Class ;
        rdfs:comment              "Category=modification." ;
        rdfs:label                "DNA-binding protein Ikaros isoform 1 phosphorylated form" ;
        rdfs:subClassOf           obo:PR_000002150 , obo:PR_000037070 ;
        rdfs:subClassOf           [ a                   owl:Restriction ;
                                    owl:onProperty      obo:BFO_0000051 ;
                                    owl:someValuesFrom  obo:MOD_00696
                                  ] ;
        obo:IAO_0000115           "A DNA-binding protein Ikaros isoform 1 that includes at least one phosphorylated residue." ;
        oboInOwl:hasExactSynonym  "IKZF1/iso:1/PhosRes+" ;
        oboInOwl:hasOBONamespace  "protein" ;
        oboInOwl:id               "PR:000018259" ;
        owl:equivalentClass       [ a                   owl:Class ;
                                    owl:intersectionOf  ( obo:PR_000002150
                                                          [ a                   owl:Restriction ;
                                                            owl:onProperty      obo:BFO_0000051 ;
                                                            owl:someValuesFrom  obo:MOD_00696
                                                          ]
                                                        )
                                  ] .

**Comment by nataled** [comment] 2019-07-08 23:15
After playing around a bit, I now see what you're saying (maybe), in that it really isn't the name of the variable that's important, it's the field name (such as rdfs:comment or rdfs:subClassOf). I determined (for example) that I can get the definition using obo:IAO_0000115. I presume that querying on a field that occurs only once would work okay (but maybe not one, such as xref, that can occur multiple times; not sure). I therefore expected that I could query over taxonomy, since it is seen only once per term and because obo:RO_0002160 (only in taxon) is mentioned on that documentation page. Unfortunately, that wasn't the case. No matter what I try I cannot even display the taxon identifier.

**Comment by chumingc** [comment] 2019-07-08 23:38
Show me the query you used and let me know exactly what you want. As I
mentioned using single triple pattern without context is not that useful.

**Comment by nataled** [comment] 2019-07-08 23:56
My short-term goal is to simply display the taxon identifier (like "NCBITaxon:9606") for retrieved entries. So while the first query below works (to display the definition), the second does not, even though I only changed IAO_0000115 to RO_0002160. Note that all I'm doing is displaying the information, not filtering based on it.

PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?PRO_term ?Category ?TextOfInterest
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:comment ?_Category .
   ?PRO_term obo:IAO_0000115 ?_TextOfInterest .
   FILTER (regex(?_Category,"Category=.*modification"))
   BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
   BIND(str(?_TextOfInterest) as ?TextOfInterest) .
}

=======

PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?PRO_term ?Category ?TextOfInterest
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:comment ?_Category .
   ?PRO_term obo:RO_0002160 ?_TextOfInterest .
   FILTER (regex(?_Category,"Category=.*modification"))
   BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
   BIND(str(?_TextOfInterest) as ?TextOfInterest) .
}

**Comment by nataled** [comment] 2019-07-09 00:08
My short-term goal is to simply display the taxon identifier (like "NCBITaxon:9606") for retrieved entries. So while the first query below works (to display the definition), the second does not, even though I only changed IAO_0000115 to RO_0002160. Note that all I'm doing is displaying the information, not filtering based on it.

PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?PRO_term ?Category ?TextOfInterest
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:comment ?_Category .
   ?PRO_term obo:IAO_0000115 ?_TextOfInterest .
   FILTER (regex(?_Category,"Category=.*modification"))
   BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
   BIND(str(?_TextOfInterest) as ?TextOfInterest) .
}

=======

PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?PRO_term ?Category ?TextOfInterest
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
   ?PRO_term rdfs:comment ?_Category .
   ?PRO_term obo:RO_0002160 ?_TextOfInterest .
   FILTER (regex(?_Category,"Category=.*modification"))
   BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
   BIND(str(?_TextOfInterest) as ?TextOfInterest) .
}

**Comment by chumingc** [comment] 2019-07-09 00:37
In PRO RDF NCBITaxon is part of OWL restriction, an "anonymous class" to express various types of constraints on classes. See highlight in the example below. 

There is no triple pattern "?PRO_term obo:RO_0002160 ?_TextOfInterest .” in the graph. Therefore, you will not be able to find match.

obo:PR_Q92599-2  a                owl:Class ;
        rdfs:comment              "Category=organism-sequence." ;
        rdfs:label                "septin-8 isoform h2 (human)" ;
        rdfs:subClassOf           obo:PR_Q92599 ;
        rdfs:subClassOf           [ a                   owl:Restriction ;
                                    owl:onProperty      obo:RO_0002160 ;
                                    owl:someValuesFrom  obo:NCBITaxon_9606
                                  ] ;
        obo:IAO_0000115           "A septin-8 (human) that is a translation product of some mRNA giving rise to a protein with the amino acid sequence represented by UniProtKB:Q92599-2." ;
        oboInOwl:hasDbXref        "UniProtKB:Q92599-2" ;
        oboInOwl:hasExactSynonym  "hSEPT8/iso:h2" , "septin-8 isoform KIAA0202a (human)" ;
        oboInOwl:hasOBONamespace  "protein" ;
        oboInOwl:id               "PR:Q92599-2" .


So the query like this will work.

PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?PRO_term ?Category ?NCBITaxon
FROM <http://purl.obolibrary.org/obo/pr>
WHERE
{
?PRO_term rdfs:comment ?_Category .
?PRO_term rdfs:subClassOf           
	[ a               owl:Restriction ;
	  owl:onProperty  obo:RO_0002160 ;
         owl:someValuesFrom  ?_NCBITaxon
       ] .
FILTER (regex(?_Category,"Category=.*modification"))
BIND(strafter(strbefore(str(?_Category), "."), "=") as ?Category) .
BIND(strafter(str(?_NCBITaxon), "_") as ?NCBITaxon) .
}

**Closed** 2020-10-09 14:00 UTC
Labels: SPARQL
